ProvisioningMaterials = {
    -- Credit for this list goes to http://tamrieljournal.com/eso-provisioning-ingredients/

    -- primary
    ["shornhelm grains"] = {tooltip = "Primary Ingredient, Level 1, Daggerfall Covenant"},
    ["capon meat"] = {tooltip = "Primary Ingredient, Level 1, Daggerfall Covenant"},
    ["aged meat"] = {tooltip = "Primary Ingredient, Level 1, Aldmeri Dominion"},
    ["pork"] = {tooltip = "Primary Ingredient, Level 1, Aldmeri Dominion"},
    ["snake slime"] = {tooltip = "Primary Ingredient, Level 1, Ebonheart Pact"},
    ["goat meat"] = {tooltip = "Primary Ingredient, Level 1, Ebonheart Pact"},
    ["iron peat"] = {tooltip = "Primary Ingredient, Level 5, Daggerfall Covenant"},
    ["battaglir weeds"] = {tooltip = "Primary Ingredient, Level 5, Daggerfall Covenant"},
    ["dusk beetle"] = {tooltip = "Primary Ingredient, Level 5, Aldmeri Dominion"},
    ["guar egg"] = {tooltip = "Primary Ingredient, Level 5, Aldmeri Dominion"},
    ["snake venom"] = {tooltip = "Primary Ingredient, Level 5, Ebonheart Pact"},
    ["kwama egg"] = {tooltip = "Primary Ingredient, Level 5, Ebonheart Pact"},
    ["tangerine"] = {tooltip = "Primary Ingredient, Level 10, Daggerfall Covenant"},
    ["bear haunch"] = {tooltip = "Primary Ingredient, Level 10, Daggerfall Covenant"},
    ["ripe apple"] = {tooltip = "Primary Ingredient, Level 10, Aldmeri Dominion"},
    ["sweetmeats"] = {tooltip = "Primary Ingredient, Level 10, Aldmeri Dominion"},
    ["wild honey"] = {tooltip = "Primary Ingredient, Level 10, Ebonheart Pact"},
    ["scuttle meat"] = {tooltip = "Primary Ingredient, Level 10, Ebonheart Pact"},
    ["wasp squeezings"] = {tooltip = "Primary Ingredient, Level 15, Daggerfall Covenant"},
    ["mutton flank"] = {tooltip = "Primary Ingredient, Level 15, Daggerfall Covenant"},
    ["wisp floss"] = {tooltip = "Primary Ingredient, Level 15, Aldmeri Dominion"},
    ["liver"] = {tooltip = "Primary Ingredient, Level 15, Aldmeri Dominion"},
    ["dragon's-tongue sap"] = {tooltip = "Primary Ingredient, Level 15, Ebonheart Pact"},
    ["plump worms"] = {tooltip = "Primary Ingredient, Level 15, Ebonheart Pact"},
    ["dark bile"] = {tooltip = "Primary Ingredient, Level 20, Daggerfall Covenant"},
    ["combwort"] = {tooltip = "Primary Ingredient, Level 20, Daggerfall Covenant"},
    ["pig’s milk"] = {tooltip = "Primary Ingredient, Level 20, Aldmeri Dominion"},
    ["goat bits"] = {tooltip = "Primary Ingredient, Level 20, Aldmeri Dominion"},
    ["sujamma berries"] = {tooltip = "Primary Ingredient, Level 20, Ebonheart Pact"},
    ["plump rodent toes"] = {tooltip = "Primary Ingredient, Level 20, Ebonheart Pact"},
    ["orc hops"] = {tooltip = "Primary Ingredient, Level 25, Daggerfall Covenant"},
    ["venison"] = {tooltip = "Primary Ingredient, Level 25, Daggerfall Covenant"},
    ["glitter rock"] = {tooltip = "Primary Ingredient, Level 25, Aldmeri Dominion"},
    ["moon sugar"] = {tooltip = "Primary Ingredient, Level 25, Aldmeri Dominion"},
    ["comberry"] = {tooltip = "Primary Ingredient, Level 25, Ebonheart Pact"},
    ["plump maggots"] = {tooltip = "Primary Ingredient, Level 25, Ebonheart Pact"},
    ["desert heather"] = {tooltip = "Primary Ingredient, Level 30, Daggerfall Covenant"},
    ["horker meat"] = {tooltip = "Primary Ingredient, Level 30, Daggerfall Covenant"},
    ["molasses"] = {tooltip = "Primary Ingredient, Level 30, Aldmeri Dominion"},
    ["crawdad"] = {tooltip = "Primary Ingredient, Level 30, Aldmeri Dominion"},
    ["river grapes"] = {tooltip = "Primary Ingredient, Level 30, Ebonheart Pact"},
    ["chaurus meat"] = {tooltip = "Primary Ingredient, Level 30, Ebonheart Pact"},
    ["black tea"] = {tooltip = "Primary Ingredient, Level 35, Daggerfall Covenant"},
    ["flank steak"] = {tooltip = "Primary Ingredient, Level 35, Daggerfall Covenant"},
    ["spring essence"] = {tooltip = "Primary Ingredient, Level 35, Aldmeri Dominion"},
    ["saltrice"] = {tooltip = "Primary Ingredient, Level 35, Aldmeri Dominion"},
    ["ash millet"] = {tooltip = "Primary Ingredient, Level 35, Ebonheart Pact"},
    ["frog legs"] = {tooltip = "Primary Ingredient, Level 35, Ebonheart Pact"},
    ["crystal berry"] = {tooltip = "Primary Ingredient, Level 40, All Alliances"},
    ["beef"] = {tooltip = "Primary Ingredient, Level 40, All Alliances"},
    ["kaveh beans"] = {tooltip = "Primary Ingredient, Level 45, All Alliances"},
    ["shank"] = {tooltip = "Primary Ingredient, Level 45, All Alliances"},
    ["mountain berries"] = {tooltip = "Primary Ingredient, Level 50, All Alliances"},
    ["mudcrab meat"] = {tooltip = "Primary Ingredient, Level 50, All Alliances"},
    ["bervez fruit"] = {tooltip = "Primary Ingredient, Level VR5, All Alliances"},
    ["jazbay grapes"] = {tooltip = "Primary Ingredient, Level VR5, All Alliances"},
    ["honey comb"] = {tooltip = "Primary Ingredient, Level VR5, All Alliances"},

    -- secondary
    ["drippings"] = {tooltip = "Secondary Ingredient, Level 1-15, Increase Max Stamina"},
    ["meal"] = {tooltip = "Secondary Ingredient, Level 1-15, Increase Max Health"},
    ["thin broth"] = {tooltip = "Secondary Ingredient, Level 1-15, Increase Max Magicka"},
    ["brown malt"] = {tooltip = "Secondary Ingredient, Level 1-15, Increase Health Recovery"},
    ["corn mash"] = {tooltip = "Secondary Ingredient, Level 1-15, Increase Stamina Recovery"},
    ["wine grapes"] = {tooltip = "Secondary Ingredient, Level 1-15, Increase Magicka Recovery"},
    ["cooking fat"] = {tooltip = "Secondary Ingredient, Level 20-25, Increase Max Stamina"},
    ["milled flour"] = {tooltip = "Secondary Ingredient, Level 20-25, Increase Max Health"},
    ["broth"] = {tooltip = "Secondary Ingredient, Level 20-25, Increase Max Magicka"},
    ["amber malt"] = {tooltip = "Secondary Ingredient, Level 20-25, Increase Health Recovery"},
    ["wheat mash"] = {tooltip = "Secondary Ingredient, Level 20-25, Increase Stamina Recovery"},
    ["grasa grapes"] = {tooltip = "Secondary Ingredient, Level 20-25, Increase Magicka Recovery"},
    ["suet"] = {tooltip = "Secondary Ingredient, Level 30-35, Increase Max Stamina"},
    ["sifted flour"] = {tooltip = "Secondary Ingredient, Level 30-35, Increase Max Health"},
    ["stock"] = {tooltip = "Secondary Ingredient, Level 30-35, Increase Max Magicka"},
    ["caramalt"] = {tooltip = "Secondary Ingredient, Level 30-35, Increase Health Recovery"},
    ["oat mash"] = {tooltip = "Secondary Ingredient, Level 30-35, Increase Stamina Recovery"},
    ["lado grapes"] = {tooltip = "Secondary Ingredient, Level 30-35, Increase Magicka Recovery"},
    ["lard"] = {tooltip = "Secondary Ingredient, Level 40-45, Increase Max Stamina"},
    ["cake flour"] = {tooltip = "Secondary Ingredient, Level 40-45, Increase Max Health"},
    ["jus"] = {tooltip = "Secondary Ingredient, Level 40-45, Increase Max Magicka"},
    ["wheat malt"] = {tooltip = "Secondary Ingredient, Level 40-45, Increase Health Recovery"},
    ["barley mash"] = {tooltip = "Secondary Ingredient, Level 40-45, Increase Stamina Recovery"},
    ["camaralet grapes"] = {tooltip = "Secondary Ingredient, Level 40-45, Increase Magicka Recovery"},
    ["fatback"] = {tooltip = "Secondary Ingredient, Level 50, Increase Max Stamina"},
    ["baker’s flour"] = {tooltip = "Secondary Ingredient, Level 50, Increase Max Health"},
    ["glace viande"] = {tooltip = "Secondary Ingredient, Level 50, Increase Max Magicka"},
    ["white malt"] = {tooltip = "Secondary Ingredient, Level 50, Increase Health Recovery"},
    ["rice mash"] = {tooltip = "Secondary Ingredient, Level 50, Increase Stamina Recovery"},
    ["ribier grapes"] = {tooltip = "Secondary Ingredient, Level 50, Increase Magicka Recovery"},
    ["pinguis"] = {tooltip = "Secondary Ingredient, Level VR5, Increase Max Stamina"},
    ["imperial flour"] = {tooltip = "Secondary Ingredient, Level VR5, Increase Max Health"},
    ["imperial stock"] = {tooltip = "Secondary Ingredient, Level VR5, Increase Max Magicka"},
    ["imperial mash"] = {tooltip = "Secondary Ingredient, Level VR5, Increase Health Recovery"},
    ["golden malt"] = {tooltip = "Secondary Ingredient, Level VR5, Increase Stamina Recovery"},
    ["emperor grapes"] = {tooltip = "Secondary Ingredient, Level VR5, Increase Magicka Recovery"},

    -- tier 2
    ["salt"] = {tooltip = "Tier 2 Ingredient, Increase Max Health"},
    ["red wheat"] = {tooltip = "Tier 2 Ingredient, Increase Max Magicka"},
    ["onion"] = {tooltip = "Tier 2 Ingredient, Increase Max Stamina"},
    ["hallertau hops"] = {tooltip = "Tier 2 Ingredient, Increase Magicka Recovery"},
    ["snowberry"] = {tooltip = "Tier 2 Ingredient, Increase Health Recovery"},
    ["concord grapes"] = {tooltip = "Tier 2 Ingredient, Increase Stamina Recovery"},

    -- tier 3
    ["garlic & pepper"] = {tooltip = "Tier 3 Ingredient"},
    ["barley & oats"] = {tooltip = "Tier 3 Ingredient"},
    ["potato & tomato"] = {tooltip = "Tier 3 Ingredient"},
    ["hops & saaz hops"] = {tooltip = "Tier 3 Ingredient"},
    ["juniper berry & canis root"] = {tooltip = "Tier 3 Ingredient"},
    ["white grapes & jazbay grapes"] = {tooltip = "Tier 3 Ingredient"},
}