ProvisioningMaterials = {
    -- Credit for this list goes to http://tamrieljournal.com/eso-provisioning-ingredients/

    -- primary
    ["shornhelm grains"] = {skillLevel = "1"},
    ["capon meat"] = {skillLevel = "1"},
    ["aged meat"] = {skillLevel = "1"},
    ["pork"] = {skillLevel = "1"},
    ["snake slime"] = {skillLevel = "1"},
    ["goat meat"] = {skillLevel = "1"},
    ["iron peat"] = {skillLevel = "5"},
    ["battaglir weeds"] = {skillLevel = "5"},
    ["dusk beetle"] = {skillLevel = "5"},
    ["guar egg"] = {skillLevel = "5"},
    ["snake venom"] = {skillLevel = "5"},
    ["kwama egg"] = {skillLevel = "5"},
    ["tangerine"] = {skillLevel = "10"},
    ["bear haunch"] = {skillLevel = "10"},
    ["ripe apple"] = {skillLevel = "10"},
    ["sweetmeats"] = {skillLevel = "10"},
    ["wild honey"] = {skillLevel = "10"},
    ["scuttle meat"] = {skillLevel = "10"},
    ["wasp squeezings"] = {skillLevel = "15"},
    ["mutton flank"] = {skillLevel = "15"},
    ["wisp floss"] = {skillLevel = "15"},
    ["liver"] = {skillLevel = "15"},
    ["dragon's-tongue sap"] = {skillLevel = "15"},
    ["plump worms"] = {skillLevel = "15"},
    ["dark bile"] = {skillLevel = "20"},
    ["combwort"] = {skillLevel = "20"},
    ["pig's milk"] = {skillLevel = "20"},
    ["goat bits"] = {skillLevel = "20"},
    ["sujamma berries"] = {skillLevel = "20"},
    ["plump rodent toes"] = {skillLevel = "20"},
    ["orc hops"] = {skillLevel = "25"},
    ["venison"] = {skillLevel = "25"},
    ["glitter rock"] = {skillLevel = "25"},
    ["moon sugar"] = {skillLevel = "25"},
    ["comberry"] = {skillLevel = "25"},
    ["plump maggots"] = {skillLevel = "25"},
    ["desert heather"] = {skillLevel = "30"},
    ["horker meat"] = {skillLevel = "30"},
    ["molasses"] = {skillLevel = "30"},
    ["crawdad"] = {skillLevel = "30"},
    ["river grapes"] = {skillLevel = "30"},
    ["chaurus meat"] = {skillLevel = "30"},
    ["black tea"] = {skillLevel = "35"},
    ["flank steak"] = {skillLevel = "35"},
    ["spring essence"] = {skillLevel = "35"},
    ["saltrice"] = {skillLevel = "35"},
    ["ash millet"] = {skillLevel = "35"},
    ["frog legs"] = {skillLevel = "35"},
    ["crystal berry"] = {skillLevel = "40"},
    ["beef"] = {skillLevel = "40"},
    ["kaveh beans"] = {skillLevel = "45"},
    ["shank"] = {skillLevel = "45"},
    ["mountain berries"] = {skillLevel = "50"},
    ["mudcrab meat"] = {skillLevel = "50"},
    ["bervez fruit"] = {skillLevel = "VR5"},
    ["jazbay grapes"] = {skillLevel = "VR5"},
    ["honey comb"] = {skillLevel = "VR5"},

    -- secondary
    ["drippings"] = {skillLevel = "1-15"},
    ["meal"] = {skillLevel = "1-15"},
    ["thin broth"] = {skillLevel = "1-15"},
    ["brown malt"] = {skillLevel = "1-15"},
    ["corn mash"] = {skillLevel = "1-15"},
    ["wine grapes"] = {skillLevel = "1-15"},
    ["cooking fat"] = {skillLevel = "20-25"},
    ["milled flour"] = {skillLevel = "20-25"},
    ["broth"] = {skillLevel = "20-25"},
    ["amber malt"] = {skillLevel = "20-25"},
    ["wheat mash"] = {skillLevel = "20-25"},
    ["grasa grapes"] = {skillLevel = "20-25"},
    ["suet"] = {skillLevel = "30-35"},
    ["sifted flour"] = {skillLevel = "30-35"},
    ["stock"] = {skillLevel = "30-35"},
    ["caramalt"] = {skillLevel = "30-35"},
    ["oat mash"] = {skillLevel = "30-35"},
    ["lado grapes"] = {skillLevel = "30-35"},
    ["lard"] = {skillLevel = "40-45"},
    ["cake flour"] = {skillLevel = "40-45"},
    ["jus"] = {skillLevel = "40-45"},
    ["wheat malt"] = {skillLevel = "40-45"},
    ["barley mash"] = {skillLevel = "40-45"},
    ["camaralet grapes"] = {skillLevel = "40-45"},
    ["fatback"] = {skillLevel = "50"},
    ["baker's flour"] = {skillLevel = "50"},
    ["glace viande"] = {skillLevel = "50"},
    ["white malt"] = {skillLevel = "50"},
    ["rice mash"] = {skillLevel = "50"},
    ["ribier grapes"] = {skillLevel = "50"},
    ["pinguis"] = {skillLevel = "VR5"},
    ["imperial flour"] = {skillLevel = "VR5"},
    ["imperial stock"] = {skillLevel = "VR5"},
    ["imperial mash"] = {skillLevel = "VR5"},
    ["golden malt"] = {skillLevel = "VR5"},
    ["emperor grapes"] = {skillLevel = "VR5"},

    -- tier 2
    ["salt"] = {tier = 2},
    ["red wheat"] = {tier = 2},
    ["onion"] = {tier = 2},
    ["hallertau hops"] = {tier = 2},
    ["snowberry"] = {tier = 2},
    ["concord grapes"] = {tier = 2},

    -- tier 3
    ["garlic"] = {tier = 3},
    ["pepper"] = {tier = 3},
    ["barley"] = {tier = 3},
    ["oats"] = {tier = 3},
    ["potato"] = {tier = 3},
    ["tomato"] = {tier = 3},
    ["hops"] = {tier = 3},
    ["saaz hops"] = {tier = 3},
    ["juniper berry"] = {tier = 3},
    ["canis root"] = {tier = 3},
    ["white grapes"] = {tier = 3},
    ["jazbay grapes"] = {tier = 3},
}